modLoader="javafml"
loaderVersion="[4,)"
license="CC-BY-NC-SA-4.0"

[[mods]]
modId="fumo"
version="17.2.0"
displayName="Fumo"
displayURL="https://modrinth.com/mod/fumo"
logoFile="logo.png"
credits="MCreator, reimuu@planetminecraft.com, mafurako@planetminecraft.com"
authors="KosherKomeiji"
description="Adds Fumos from Touhou."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.fumo]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.fumo]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration